### ISSUE TITLE
A difference

### ISSUE THREAD

**Issue by mckuhei** [SuperSodaSea/Omniscent#1]
If use hardware renderer, Lava's light will not visible.
![image](https://user-images.githubusercontent.com/31839741/147349633-383864e2-81e1-4e94-ba5d-8813e5b6c19c.png)
![image](https://user-images.githubusercontent.com/31839741/147349724-1b74219f-7030-4053-970c-011d363e817e.png)

**Comment by SuperSodaSea** [comment]
This problem is caused by the special palette of the texture:
https://github.com/SuperSodaSea/Omniscent/blob/49b5f72743dd4656b39350e2abff01c05737e1d0/Omniscent.js#L567-L585
At line 574 the palette don't start at completely black, but at a dark red color (RGB value = (0x18, 0x04, 0x00)), and makes the texture seems to be "lighten" by lava.
However, the hardware render just simply calculate the color by multiplying the texture's color by light intensity, which ignores the special red color of the palette.
I will try to fix this problem some time later.

For reference, this is the origional palette (notice the dark red at 0x5F compared with the black at 0x1F, 0x3F, etc):
![Palette256](https://user-images.githubusercontent.com/8724868/147366587-f33a7b4b-4dc3-4c8a-9b6d-0ff9f19081ec.png)

**Comment by SuperSodaSea** [comment]
Problem solved.
